# Generated by Django 4.2.14 on 2024-08-23 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('cover', models.ImageField(blank=True, upload_to='covers/', verbose_name='Cover')),
                ('status', models.CharField(choices=[('pub', 'Published'), ('drf', 'Draft')], default='pub', max_length=3, verbose_name='Status')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='DateTimeCreated')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='DateTimeModified')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('helpful', models.BooleanField(default=True, verbose_name='Post Was helpful?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is_active')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='DateTimeCreated')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='DateTimeModified')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
