# Generated by Django 4.2.14 on 2024-07-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='helpful',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
